name: example
description: "Example project for the repo_notifier package."
publish_to: 'none'
version: 1.0.0-beta.1

environment:
  sdk: ^3.6.0-334.4.beta
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  repo_notifier:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
